# Shared prefix block. Prepend to any query in this directory.
PREFIX aia:      <https://w3id.org/aia-ont#>
PREFIX eli:      <http://data.europa.eu/eli/ontology#>
PREFIX skos:     <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:      <http://www.w3.org/2002/07/owl#>
PREFIX airo:     <https://w3id.org/airo#>
PREFIX vair:     <https://w3id.org/vair#>
PREFIX dpv:      <https://w3id.org/dpv/owl#>
PREFIX org:      <http://www.w3.org/ns/org#>
PREFIX prov:     <http://www.w3.org/ns/prov#>
PREFIX eu-aiact: <https://w3id.org/dpv/legal/eu/aiact/owl#>
