"""Compute the evaluation metrics defined in ../reports/evaluation.md.

Output sections:

  1. Consistency       OWL 2 RL consistency of core + worked example + imports
                       (HermiT is run separately by run-hermit.sh)
  2. Answerability     per CQ: rows, bound cells, dependence on inference
  3. Annotation        label / definition / article anchor per local term
  4. Legal coverage    modelled provisions against the GOLD enumeration below

Expert legal review, the fifth metric, is manual and described in evaluation.md.

Writes ../reports/metrics-results.md.
Run from the repository root:  python3 scripts/compute-metrics.py
Needs: rdflib, owlrl.
"""
import os, re
from collections import Counter
import rdflib
from rdflib import RDF, RDFS, OWL, URIRef
from owlrl import OWLRL_Semantics

ROOT   = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ONT    = os.path.join(ROOT, "ontology")
Q      = os.path.join(ROOT, "queries")
OUT    = os.path.join(ROOT, "reports", "metrics-results.md")
IMPORTS = [("eu-aiact-owl.ttl", "turtle"), ("airo.ttl", "turtle"),
           ("eli.owl", "xml"), ("skos.rdf", "xml")]
ORDER = ["cq1-risk-category.rq", "cq1-highrisk-entailment.rq",
         "cq2-prohibited-practices.rq", "cq3-actor-obligations.rq",
         "cq4-role-reassignment.rq", "cq5-oversight-conformity.rq"]

AIA  = rdflib.Namespace("https://w3id.org/aia-ont#")
SKOS = rdflib.Namespace("http://www.w3.org/2004/02/skos/core#")
ELI  = rdflib.Namespace("http://data.europa.eu/eli/ontology#")
AIA_NS = str(AIA)

# ── Gold enumeration of the in-scope provisions ─────────────────────────────
# Taken from the Act's own numbering (Official Journal, consolidated text of
# 27.07.2026 incorporating Regulation (EU) 2026/1744), NOT from
# the ontology, so that a missing individual shows up as a coverage gap rather
# than silently shrinking the denominator. Art. 26(3) is a savings clause and
# imposes no duty; it is listed as excluded so the exclusion stays visible.
GOLD = [
    ("Art. 3(8) operator roles", ["Provider", "Deployer", "AuthorisedRepresentative",
                                  "Importer", "Distributor", "ProductManufacturer"], {}),
    ("Art. 5(1) prohibited practices",
     [f"pp_art5_1_{c}" for c in ["a", "b", "ba", "bb", "c", "d", "e", "f", "g", "h"]], {}),
    ("Art. 16 provider obligations", [f"ob_art16_{c}" for c in "abcdefghijkl"], {}),
    ("Art. 25(2) residual duties of the initial provider",
     ["ob_art25_2_cooperate", "ob_art25_2_a", "ob_art25_2_b", "ob_art25_2_c"], {}),
    ("Art. 25(1) promotion circumstances", ["rc_art25_1_a_own_name",
                                            "rc_art25_1_b_substantial_modification",
                                            "rc_art25_1_c_purpose_modification"], {}),
    ("Art. 26 deployer obligations", [f"ob_art26_{n}" for n in range(1, 13)],
     {"ob_art26_3": "savings clause, imposes no duty"}),
]
ACT_ARTICLES, ACT_ANNEXES = 113, 13


def parse(path, fmt="turtle"):
    g = rdflib.Graph(); g.parse(path, format=fmt); return g

def local(t):
    return isinstance(t, URIRef) and str(t).startswith(AIA_NS)

def short(t):
    s = str(t)
    return "aia:" + s[len(AIA_NS):] if s.startswith(AIA_NS) else s.rsplit("/", 1)[-1]

def pct(n, d):
    return f"{n}/{d} ({100*n/d:.0f}%)" if d else "0/0"


# ═══════════════════════════════════════════════════════════════════════════
print("loading …")
core    = parse(os.path.join(ONT, "aia-ont.ttl"))
example = parse(os.path.join(ONT, "aia-example.ttl"))
imports = {f: parse(os.path.join(ONT, "imports", f), fmt) for f, fmt in IMPORTS}
queries = {q: open(os.path.join(Q, q)).read() for q in ORDER}

def assemble():
    g = rdflib.Graph()
    for part in (core, example, *imports.values()):
        g += part
    return g

ANCHORS = tuple(core.transitive_subjects(RDFS.subPropertyOf, AIA.definedIn))
classes  = {s for s in core.subjects(RDF.type, OWL.Class) if local(s)}
oprops   = {s for s in core.subjects(RDF.type, OWL.ObjectProperty) if local(s)}
indivs   = {s for s in core.subjects(RDF.type, OWL.NamedIndividual) if local(s)}
articles = {s for s in core.subjects(RDF.type, ELI.LegalResourceSubdivision) if local(s)}
md = ["# Evaluation Metrics: Computed Values", "",
      "*Generated by `scripts/compute-metrics.py`; do not edit. Definitions and the manual "
      "method: `evaluation.md`.*", ""]
summary = []   # (metric, value) for the headline table

def section(title):
    print(f"\n{title}\n" + "-" * len(title)); md.extend([f"## {title}", ""])

def table(header, rows):
    md.append("| " + " | ".join(header) + " |")
    md.append("|" + "---|" * len(header))
    for r in rows:
        md.append("| " + " | ".join(str(c) for c in r) + " |")
    md.append("")


# ═══ 1. Consistency ════════════════════════════════════════════════════════
section("1. Consistency")
def closure(g):
    r = OWLRL_Semantics(g, False, False, False)
    r.closure(); r.flush_stored_triples()
    return getattr(r, "error_messages", [])

def answers(g):
    """One comparable signature per query: a frozenset of rows, or a boolean."""
    out = {}
    for q, src in queries.items():
        res = g.query(src)
        out[q] = bool(res.askAnswer) if res.type == "ASK" else frozenset(
            tuple(str(v) if v is not None else None for v in row) for row in res)
    return out

asserted_ans = answers(assemble())
inferred = assemble(); base_errors = closure(inferred)
base_ans = answers(inferred)
md += [f"OWL 2 RL (`owlrl`) over the core, the worked example and the four imports: "
       f"{len(base_errors)} inconsistencies. HermiT, as bundled with Protégé 5.6.9, is run by "
       "`scripts/run-hermit.sh`; its output is in `evidence/hermit-full-run.log`.", ""]
print(f"  OWL 2 RL inconsistencies: {len(base_errors)}")
summary.append(("OWL 2 RL inconsistencies", str(len(base_errors))))


# ═══ 2. Answerability ══════════════════════════════════════════════════════
section("2. Competency-question answerability")
rows, cells_b, cells_t, returned = [], 0, 0, 0
for q in ORDER:
    if isinstance(base_ans[q], bool):
        rows.append((f"`{q}`", "ASK", f"{asserted_ans[q]} → **{base_ans[q]}**", "—", "yes" if asserted_ans[q] != base_ans[q] else "no"))
        returned += base_ans[q]
        continue
    res = inferred.query(queries[q]); r = list(res); n = len(r); k = len(res.vars)
    b = sum(v is not None for row in r for v in row)
    cells_b += b; cells_t += n * k; returned += n > 0
    dep = base_ans[q] != asserted_ans[q]
    rows.append((f"`{q}`", n, f"{len(asserted_ans[q])} → {n}", pct(b, n * k), "yes" if dep else "no"))
table(["Query", "Rows (inferred)", "Asserted → inferred", "Projected cells bound", "Answer depends on inference"], rows)
md += [f"{returned}/{len(ORDER)} queries return.", "",
       "Unbound cells are not necessarily defects (e.g. the minimal-risk system has no ground); "
       "see `cq-results.md`.", ""]
for r in rows: print(f"  {r[0]:34} {r[1]!s:5} {r[2]:14} bound {r[3]:16} inference-dependent {r[4]}")
summary += [("CQ queries returning (5 CQs + the CQ1 ASK)", f"{returned}/{len(ORDER)}"),
            ("Projected cells bound across SELECT CQs", pct(cells_b, cells_t))]


# ═══ 3. Annotation completeness ════════════════════════════════════════════
section("3. Annotation completeness")
terms = {"class": classes, "object property": oprops, "individual": indivs - articles}
has_art_cite = lambda s: any(re.search(r"\b(Arts?\.|Articles?|Annex(es)?|Recitals?)\s", str(c))
                             for c in core.objects(s, RDFS.comment))
rows, totals = [], Counter()
for kind, S in terms.items():
    lab = {s for s in S if (s, SKOS.prefLabel, None) in core}
    dfn = {s for s in S if (s, SKOS.definition, None) in core}
    art = {s for s in S if any((s, p, None) in core for p in ANCHORS)}
    txt = {s for s in S - art if has_art_cite(s)}
    rows.append((kind, len(S), pct(len(lab), len(S)), pct(len(dfn), len(S)),
                 pct(len(art), len(S)), pct(len(txt), len(S)), len(S) - len(art) - len(txt)))
    totals.update(n=len(S), lab=len(lab), dfn=len(dfn), art=len(art), txt=len(txt))
rows.append(("**all**", totals["n"], pct(totals["lab"], totals["n"]), pct(totals["dfn"], totals["n"]),
             pct(totals["art"], totals["n"]), pct(totals["txt"], totals["n"]),
             totals["n"] - totals["art"] - totals["txt"]))
table(["Term kind", "n", "`skos:prefLabel`", "`skos:definition`", "Article anchor (machine-readable)",
       "Article cited in comment only", "No article reference"], rows)
md.append("Article anchor: an `aia:definedIn` edge (or subproperty) to an article resource. "
          "Citations in `rdfs:comment` only are counted separately; they are not queryable.")
md.append("")
for r in rows: print(f"  {r[0]:18} n={r[1]:<3} label {r[2]:12} defn {r[3]:12} anchor {r[4]:12} comment-only {r[5]}")
summary += [("Label / definition completeness", f"{pct(totals['lab'], totals['n'])} / {pct(totals['dfn'], totals['n'])}"),
            ("Machine-readable article anchor", pct(totals["art"], totals["n"]))]


# ═══ 4. Legal coverage ═════════════════════════════════════════════════════
section("4. Legal coverage")
merged_local = core + example
rows, cov_n, cov_d, missing = [], 0, 0, []
for name, ids, excluded in GOLD:
    inscope = [i for i in ids if i not in excluded]
    present = [i for i in inscope if (AIA[i], None, None) in merged_local]
    in_core = [i for i in present if (AIA[i], None, None) in core]
    missing += [f"{name}: aia:{i}" for i in inscope if i not in present]
    note = "; ".join(f"{k[3:]} excluded — {v}" for k, v in excluded.items()) or ""
    if len(in_core) < len(present):
        note = (note + "; " if note else "") + f"{len(present)-len(in_core)} defined only in the worked example"
    rows.append((name, pct(len(present), len(inscope)), note or "—"))
    cov_n += len(present); cov_d += len(inscope)
table(["Provision group", "Modelled / in scope", "Note"], rows)
arts = sum(1 for a in articles if short(a).startswith("aia:art_"))
anx  = sum(1 for a in articles if short(a).startswith("aia:annex_"))
md += [f"Depth over in-scope provisions: {pct(cov_n, cov_d)}. "
       f"Breadth: {arts}/{ACT_ARTICLES} articles and {anx}/{ACT_ANNEXES} annexes have an article "
       "resource. Scope: `report.md` §1.", ""]
if missing:
    md += ["Missing: " + ", ".join(missing), ""]
for r in rows: print(f"  {r[0]:40} {r[1]:14} {r[2]}")
print(f"  breadth: {arts}/{ACT_ARTICLES} articles, {anx}/{ACT_ANNEXES} annexes")
summary += [("Provision coverage (in-scope depth)", pct(cov_n, cov_d)),
            ("Article breadth over the Act", f"{arts}/{ACT_ARTICLES} articles, {anx}/{ACT_ANNEXES} annexes")]


# ═══ Headline ══════════════════════════════════════════════════════════════
head = ["## Summary", ""]
head += ["| Metric | Value |", "|---|---|"] + [f"| {k} | {v} |" for k, v in summary] + [""]
md[4:4] = head
open(OUT, "w").write("\n".join(md) + "\n")
print(f"\nwrote {os.path.relpath(OUT, ROOT)}")
