"""Run the competency-question queries over the asserted and the inferred graph.

Loads core + worked example + the four imports, computes the OWL 2 RL closure,
and runs every .rq file in ../queries/ (with prefixes.rq) against both the
asserted and the inferred graph, recording row counts for each.

The inferred graph is the one the queries are written for:

  * CQ1's ASK holds only through aia:HighRiskByGround; no file asserts that an
    example system is a eu-aiact:HighRiskAISystem.
  * CQ5 matches the market surveillance authority against two authority types
    only after subsumption (MarketSurveillanceAuthority is a subclass of
    NationalCompetentAuthority in eu-aiact).
  * CQ3 and CQ4 read Article 25(2) through aia:TerminatedRoleAssignment, which
    is entailed from the recorded reassignment.

Writes ../reports/cq-results.md and prints a summary. Exit status is non-zero
if any query returns no rows.

Run from the repository root:  python3 scripts/run-cq-queries.py
Needs: rdflib, owlrl.
"""
import os, re, sys
import rdflib
from owlrl import OWLRL_Semantics

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ONT  = os.path.join(ROOT, "ontology")
Q    = os.path.join(ROOT, "queries")
OUT  = os.path.join(ROOT, "reports", "cq-results.md")
IMPORTS = [("eu-aiact-owl.ttl", "turtle"), ("airo.ttl", "turtle"),
           ("eli.owl", "xml"), ("skos.rdf", "xml")]

# Query order is the order of the competency questions, not alphabetical.
ORDER = ["cq1-risk-category.rq", "cq1-highrisk-entailment.rq",
         "cq2-prohibited-practices.rq", "cq3-actor-obligations.rq",
         "cq4-role-reassignment.rq", "cq5-oversight-conformity.rq"]

# Columns whose values are whole sentences. Printed as a binding count rather
# than as table cells -- they are projected to make the annotation requirement
# testable, and a 300-character cell tests it no better than a tick does.
PROSE = {"categoryDefinition", "practiceDefinition", "obligationDefinition"}

PREFIXES = [
    ("aia:",      "https://w3id.org/aia-ont#"),
    ("eu-aiact:", "https://w3id.org/dpv/legal/eu/aiact/owl#"),
    ("airo:",     "https://w3id.org/airo#"),
    ("eli:",      "http://data.europa.eu/eli/ontology#"),
    ("dpv:",      "https://w3id.org/dpv/owl#"),
    ("org:",      "http://www.w3.org/ns/org#"),
    ("act:",      "http://data.europa.eu/eli/reg/2024/1689/oj"),
]

def shorten(term):
    if term is None:
        return "—"
    if isinstance(term, rdflib.URIRef):
        s = str(term)
        for pfx, ns in PREFIXES:
            if s.startswith(ns):
                return pfx + s[len(ns):] if s != ns else pfx.rstrip(":")
        return f"<{s}>"
    s = re.sub(r"\s+", " ", str(term)).strip()
    return s if len(s) <= 78 else s[:75] + "…"

def load(infer):
    g = rdflib.Graph()
    g.parse(os.path.join(ONT, "aia-ont.ttl"), format="turtle")
    g.parse(os.path.join(ONT, "aia-example.ttl"), format="turtle")
    for f, fmt in IMPORTS:
        g.parse(os.path.join(ONT, "imports", f), format=fmt)
    if not infer:
        return g, []
    r = OWLRL_Semantics(g, False, False, False)
    r.closure(); r.flush_stored_triples()
    return g, getattr(r, "error_messages", [])

print("loading core + worked example + 4 imports …")
asserted, _ = load(False)
inferred, errors = load(True)
print(f"  asserted {len(asserted):,} triples; inferred closure {len(inferred):,} triples")
print(f"  inconsistencies reported by the reasoner: {len(errors)}")

lines = ["# Competency-question results",
         "",
         "*Generated by `scripts/run-cq-queries.py`. Do not edit by hand.*",
         "",
         "Graph: `ontology/aia-ont.ttl` + `ontology/aia-example.ttl` + the four vendored ",
         "imports, closed under OWL 2 RL (`owlrl`). The alignment module is **not** loaded: ",
         "no query binds a PROV-O, ORG-property or ODRL term, and loading it would make the ",
         "results depend on axioms the core deliberately does not carry. `org:Organization`, ",
         "which CQ5 does bind, is stubbed in the worked example itself.",
         "",
         f"| | |\n|---|---|\n| Asserted triples | {len(asserted):,} |",
         f"| Inferred closure | {len(inferred):,} |",
         f"| Inconsistencies | **{len(errors)}** |",
         ""]

failures, summary = [], []

for fn in ORDER:
    path = os.path.join(Q, fn)
    src  = open(path).read()
    # The question itself is the first comment paragraph of the .rq file.
    head = []
    for l in src.splitlines():
        if not l.startswith("#"):
            break
        t = l.lstrip("#").strip()
        if not t:
            break
        head.append(t)
    title = " ".join(head) if head else fn
    is_ask = re.search(r"^\s*ASK", src, re.M | re.I) is not None

    ra = asserted.query(src)
    ri = inferred.query(src)

    lines += [f"## `{fn}`", "", f"*{title}*", ""]

    if is_ask:
        a, i = bool(ra.askAnswer), bool(ri.askAnswer)
        lines += [f"| Graph | Answer |", "|---|---|",
                  f"| asserted | `{a}` |", f"| **inferred** | **`{i}`** |", ""]
        summary.append((fn, "ASK", str(a), str(i)))
        if not i:
            failures.append(f"{fn}: ASK is false over the inferred graph")
        print(f"  {fn:32} ASK asserted={a}  inferred={i}")
        continue

    rows = list(ri)
    cols = [str(v) for v in ri.vars]
    shown = [c for c in cols if c not in PROSE]
    summary.append((fn, "SELECT", str(len(list(ra))), str(len(rows))))
    print(f"  {fn:32} rows asserted={len(list(ra)):<4} inferred={len(rows)}")
    if not rows:
        failures.append(f"{fn}: returns no rows")

    lines += [f"**{len(rows)} rows** over the inferred graph "
              f"({len(list(ra))} over the asserted graph).", ""]

    # per-column binding completeness, over every projected variable
    lines += ["| Projected variable | Rows bound |", "|---|---|"]
    for c in cols:
        n = sum(1 for r in rows if r[c] is not None)
        mark = "" if n == len(rows) else " ⚠"
        note = " *(prose column, not printed below)*" if c in PROSE else ""
        lines.append(f"| `?{c}`{note} | {n} / {len(rows)}{mark} |")
    lines.append("")

    if shown:
        lines.append("| " + " | ".join(f"`?{c}`" for c in shown) + " |")
        lines.append("|" + "---|" * len(shown))
        for r in rows:
            lines.append("| " + " | ".join(shorten(r[c]) for c in shown) + " |")
        lines.append("")

lines += ["## Summary", "",
          "| Query | Form | Asserted | Inferred |", "|---|---|---|---|"]
for fn, form, a, i in summary:
    lines.append(f"| `{fn}` | {form} | {a} | {i} |")
lines.append("")
lines += ["Every competency question returns. Where the two columns differ, the difference",
          "is the reasoner's contribution and is explained in the header comment of",
          "`scripts/run-cq-queries.py`.", ""]

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, "w").write("\n".join(lines))
print(f"\nwrote {os.path.relpath(OUT, ROOT)}")

if errors:
    print(f"\n**INCONSISTENT** — {errors[0]}")
if failures:
    print("\n" + "\n".join("**FAIL** " + f for f in failures))
    sys.exit(1)
print("all five competency questions return rows")
sys.exit(1 if errors else 0)
